config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#index'
  resources :promotions, only: %i[index]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/promotion.rb
class Promotion < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
    end
end

app/controllers/promotions_controller.rb
class PromotionsController < ApplicationController
    def index
        @promotions = Promotion.all
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<h1>Promotion System</h1>

<h3>Boas vindas ao sistema de gestão de promoções</h3>

<br><%= link_to 'Promoções', promotions_path %><br/>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IuguEtapa1</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/promotions/index.html.erb
<% @promotions.each do |promotion| %>
    <h3><%= promotion.name %></h3>
    <dl>
        <dt>Descrição</dt>
        <dd><%= promotion.description %></dd>
        <dt>Desconto <small>em porcentagem</small></dt>
        <dd><%= number_to_percentage promotion.discount_rate, separator: ',', precision: 2 %></dd>
    </dl>
<%end%>